//Create GuessingGame class in which user can play game by chossing the number
// from 0 to 100 and the number is generated by computer with in a limit of 5.
import java.util.Scanner;
public class GuessingGame{
	public static void main(String[] args){
		Scanner input = new Scanner(System.in);
		System.out.println("Welcome to number guess game.");
		int count = 0;
		int userInput;
		//computer generate number from 0 to 100
		int computerGeneratedNumber = (int)((Math.random()*90)+11);
		do{
			System.out.println("Enter number from 0 to 100 only: ");
			//user choose number from 0 to 100
			userInput = input.nextInt();
			if(userInput < computerGeneratedNumber){
				System.out.println("Too low");
			}else{
				System.out.println("Too high");
			}
			count++;
		}while(computerGeneratedNumber != userInput && count != 5);
		if(count == 5){
			System.out.println("you have excessed the limit.The computer generate number is "+
								computerGeneratedNumber);
		}
	}
}